import React, { useState, useEffect } from 'react';
import ReportViewer from '../components/ReportViewer';
import { useReportData, getAvailableReports, getCurrentPeriod, MONTH_NAMES } from '../hooks/useReportData';
import { Download, Loader2 } from 'lucide-react';
import html2pdf from 'html2pdf.js';

const PublicView = () => {
    const currentPeriod = getCurrentPeriod();
    const [availableReports, setAvailableReports] = useState([]);
    const [selectedYear, setSelectedYear] = useState(currentPeriod.year);
    const [selectedMonth, setSelectedMonth] = useState(currentPeriod.month);
    const [isDownloading, setIsDownloading] = useState(false);

    const { reportData } = useReportData(selectedYear, selectedMonth);

    // Load available reports on mount
    useEffect(() => {
        const reports = getAvailableReports();
        setAvailableReports(reports);

        // If current month has no report, default to most recent available
        if (reports.length > 0) {
            const currentExists = reports.some(r => r.year === currentPeriod.year && r.month === currentPeriod.month);
            if (!currentExists) {
                setSelectedYear(reports[0].year);
                setSelectedMonth(reports[0].month);
            }
        }
    }, []);

    const selectedMonthLabel = `${MONTH_NAMES[selectedMonth - 1]} ${selectedYear}`;

    const handleDownload = () => {
        setIsDownloading(true);
        const element = document.getElementById('report-content');

        const opt = {
            margin: 0,
            filename: `EHS_Report_${selectedMonthLabel.replace(/\s+/g, '_')}.pdf`,
            image: { type: 'jpeg', quality: 0.98 },
            html2canvas: {
                scale: 2,
                useCORS: true,
                logging: false
            },
            jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' }
        };

        document.body.classList.add('pdf-generating');

        html2pdf().set(opt).from(element).toPdf().get('pdf').then((pdf) => {
            const totalPages = pdf.internal.getNumberOfPages();
            const pageWidth = pdf.internal.pageSize.getWidth();
            const pageHeight = pdf.internal.pageSize.getHeight();

            for (let i = 1; i <= totalPages; i++) {
                pdf.setPage(i);

                if (i > 1) {
                    pdf.setFontSize(8);
                    pdf.setTextColor(150, 150, 150);
                    pdf.text(`EHS Monthly Report - ${selectedMonthLabel}`, 10, 10);

                    pdf.setDrawColor(200, 200, 200);
                    pdf.setLineWidth(0.1);
                    pdf.line(10, 12, pageWidth - 10, 12);
                }

                pdf.setFontSize(8);
                pdf.setTextColor(150, 150, 150);
                const footerText = `Page ${i} of ${totalPages}`;
                pdf.text(footerText, pageWidth - 30, pageHeight - 10);

                pdf.text("Generated by EHS Portal", 10, pageHeight - 10);
            }
        }).save().then(() => {
            document.body.classList.remove('pdf-generating');
            setIsDownloading(false);
        }).catch(err => {
            console.error("PDF Generation Error:", err);
            document.body.classList.remove('pdf-generating');
            setIsDownloading(false);
            alert("Failed to generate PDF. Please try again.");
        });
    };

    // Combined change handler for year/month dropdown
    const handlePeriodChange = (e) => {
        const [year, month] = e.target.value.split('-').map(Number);
        setSelectedYear(year);
        setSelectedMonth(month);
    };

    return (
        <div className="space-y-4 md:space-y-6">
            {/* Toolbar / Filter Bar */}
            <div className="glass p-3 md:p-4 rounded-xl md:rounded-2xl flex flex-row items-center justify-between gap-3 md:gap-4 sticky top-14 md:top-20 z-40 transition-shadow duration-300 hover:shadow-md">
                <div className="flex items-center gap-2 md:gap-3">
                    <div className="w-1 md:w-1.5 h-5 md:h-6 bg-brand-500 rounded-full shadow-lg shadow-brand-200" />
                    <h2 className="text-sm md:text-lg font-bold text-slate-800 tracking-tight">Report Browser</h2>
                </div>

                <div className="flex items-center gap-2 md:gap-3">
                    <select
                        className="bg-slate-50 border border-slate-200 text-slate-700 text-xs md:text-sm font-medium rounded-lg focus:ring-2 focus:ring-brand-500/20 focus:border-brand-500 block w-32 md:w-48 p-2 md:p-2.5 transition-all outline-none"
                        value={`${selectedYear}-${selectedMonth}`}
                        onChange={handlePeriodChange}
                    >
                        {availableReports.length > 0 ? (
                            availableReports.map(report => (
                                <option key={`${report.year}-${report.month}`} value={`${report.year}-${report.month}`}>
                                    {MONTH_NAMES[report.month - 1]} {report.year}
                                </option>
                            ))
                        ) : (
                            <option value={`${currentPeriod.year}-${currentPeriod.month}`}>
                                {MONTH_NAMES[currentPeriod.month - 1]} {currentPeriod.year}
                            </option>
                        )}
                    </select>

                    <button
                        onClick={handleDownload}
                        disabled={isDownloading}
                        title="Download PDF"
                        className="p-2 md:p-2.5 text-slate-500 hover:text-brand-600 hover:bg-brand-50 rounded-lg transition-colors border border-slate-200/50 hover:border-brand-200 disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
                    >
                        {isDownloading ? (
                            <Loader2 className="w-4 h-4 md:w-5 md:h-5 animate-spin text-brand-500" />
                        ) : (
                            <Download className="w-4 h-4 md:w-5 md:h-5" />
                        )}
                    </button>
                </div>
            </div>

            {/* Report Content */}
            <div id="report-content">
                <ReportViewer data={reportData} month={selectedMonthLabel} />
            </div>
        </div>
    );
};

export default PublicView;
